
networks:
  sipnet:
    driver: bridge

services:

  kamailio:
    build: ./kamailio
    container_name: kamailio
    restart: always
    ports:
      - "443:443/tcp"
      - "5060:5060/udp"
    environment:
      - DOMAIN=${DOMAIN}
      - FREESWITCH_IP=${FREESWITCH_IP}
    depends_on:
      - rtpengine
    networks:
      - sipnet

  rtpengine:
    image: drachtio/rtpengine
    container_name: rtpengine
    restart: always
    networks:
      - sipnet
    volumes:
      - ./rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf
    command: -f /etc/rtpengine/rtpengine.conf
