
services:

  kamailio:
    image: sip-lab-kamailio
    container_name: kamailio
    restart: always
    ports:
      - "443:443/tcp"
      - "5060:5060/udp"
    environment:
      - DOMAIN=${DOMAIN}
      - FREESWITCH_IP=${FREESWITCH_IP}
    depends_on:
      - rtpengine
    network_mode: host
    volumes:
    - ./kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg

  rtpengine:
    image: drachtio/rtpengine
    container_name: rtpengine
    restart: always
    network_mode: host
    command: >
      rtpengine
      --interface=192.168.100.6
      --listen-ng=127.0.0.1:2223
      --port-min=30000
      --port-max=40000
