[rtpengine]

# IP address of VM1 (Kamailio + RTPengine)
interface = 192.168.100.6

# Socket used by Kamailio
listen-ng = 127.0.0.1:2223

# RTP media port range
port-min = 30000
port-max = 40000

# Logging
log-level = 6

# Timeouts
timeout = 60
silent-timeout = 3600

# NAT handling
tos = 184

